1|"""Random tips shown at CLI session start to help users discover features."""
2|
3|import random
4|
5|
6|# ---------------------------------------------------------------------------
7|# Tip corpus — one-liners covering slash commands, CLI flags, config,
8|# keybindings, tools, gateway, skills, profiles, and workflow tricks.
9|# ---------------------------------------------------------------------------
10|
11|TIPS = [
13|    "/background <prompt>（别名 /bg 或 /btw）在独立会话中运行任务，当前会话保持空闲。",
14|    "/branch 分叉当前会话，可以探索不同方向而不丢失进度。",
15|    "/compress 手动压缩对话上下文，适用于对话过长时。",
16|    "/rollback 列出文件系统检查点 — 将 agent 修改过的文件恢复到任意先前状态。",
17|    "/rollback diff 2 预览检查点 2 之后的变更，不执行恢复。",
18|    "/rollback 2 src/file.py 从特定检查点恢复单个文件。",
19|    "/title \"项目名\" 为会话命名 — 之后可用 /resume 或 hermes -c 恢复。",
20|    "/resume 从之前命名的会话中断处继续。",
21|    "/queue <prompt> 将消息排队到下一轮，不打断当前处理。",
22|    "/undo 从对话中移除最后一条用户/助手交互。",
23|    "/retry 重新发送上一条消息 — 当 agent 的回答不太对时很有用。",
24|    "/verbose 循环切换工具进度显示：关 → 新工具 → 全部 → 详细。",
25|    "/reasoning high 提高模型思考深度。/reasoning show 显示推理过程。",
26|    "/reasoning low 或 /reasoning minimal 将思考深度降低到默认（medium）以下 — 更快、更便宜的响应。",
27|    "/fast 切换优先处理模式，获得更快的 API 响应（取决于提供商）。",
28|    "/yolo 跳过当前会话剩余时间内的所有危险命令审批提示。",
29|    "/model 可以在会话中途切换模型 — 试试 /model sonnet 或 /model gpt-5。",
30|    "/model --global 永久更改默认模型。",
31|    "/personality pirate 设置有趣的人格 — 内置 14 种风格，从可爱到莎士比亚。",
32|    "/skin 更改 CLI 主题 — 试试 ares、mono、slate、poseidon 或 charizard。",
33|    "/statusbar 切换常驻状态栏，显示模型、token 数、上下文填充率、费用和耗时。",
34|    "/tools disable browser 临时移除当前会话的浏览器工具。",
35|    "/browser connect 通过 CDP 将浏览器工具连接到你正在运行的 Chrome 实例。",
36|    "/plugins 列出已安装的插件及其状态。",
37|    "/cron 管理定时任务 — 设置定期执行的提示，支持投递到任意平台。",
38|    "/reload-mcp 热重载 MCP 服务器配置，无需重启。",
39|    "/usage 显示 token 用量、费用明细和会话时长。",
40|    "/insights 显示最近 30 天的使用分析。",
41|    "/paste 检查剪贴板中的图片并附加到下一条消息。",
42|    "/profile 显示当前活跃的配置文件及其主目录。",
43|    "/config 一目了然地查看当前配置。",
44|    "/stop 终止 agent 启动的所有后台进程。",
45|    "@file:path/to/file.py 将文件内容直接注入到你的消息中。",
46|    "@file:main.py:10-50 只注入文件的第 10-50 行。",
47|    "@folder:src/ 注入目录树列表。",
48|    "@diff 将未暂存的 git 变更注入到消息中。",
49|    "@staged 将已暂存的 git 变更注入（git diff --staged）。",
50|    "@git:5 注入最近 5 次提交及其完整补丁。",
51|    "@url:https://example.com 获取并注入网页内容。",
52|    "输入 @ 触发文件路径自动补全 — 交互式导航到任意文件。",
53|    "Alt+Enter（或 Ctrl+J）插入换行，用于多行输入。",
54|    "Ctrl+C 中断 agent。2 秒内连按两次强制退出。",
55|    "Ctrl+Z 将 Hermes 挂起到后台 — 在 shell 中运行 fg 恢复。",
56|    "Tab 接受自动建议的补全文本或自动补全斜杠命令。",
57|    "在 agent 工作时输入新消息可以中断并重新引导它。",
58|    "Alt+V 将剪贴板中的图片粘贴到对话中。",
59|    "粘贴 5 行以上内容时会自动保存为文件，并插入一个紧凑引用代替。",
60|    " 按标题恢复。",
61|    "hermes -w 创建隔离的 git worktree — 适合并行 agent 工作流。",
62|    " 结合 worktree 隔离和一次性查询。",
63|    "hermes chat -t web,terminal 只启用指定工具集，进行专注会话。",
64|    "hermes chat -s github-pr-workflow 启动时预加载技能。",
65|    " 运行单次非交互查询并退出。",
66|    "hermes chat --max-turns 200 覆盖默认的每轮 90 次迭代限制。",
67|    "hermes chat --checkpoints 在每次破坏性文件变更前启用文件系统快照。",
68|    "hermes --yolo 跳过整个会话的所有危险命令审批提示。",
69|    "hermes chat --source telegram 为会话打标签，方便在 hermes sessions list 中筛选。",
70|    "hermes -p work chat 在指定配置文件下运行，不改变默认配置。",
71|    "hermes doctor --fix 诊断并自动修复配置和依赖问题。",
72|    "hermes dump 输出精简的设置摘要 — 适合提交 bug 报告。",
73|    "hermes config set KEY VALUE 自动将密钥路由到 .env，其他内容路由到 config.yaml。",
74|    "hermes config edit 在默认编辑器中打开 config.yaml。",
75|    "hermes config check 扫描缺失或过时的配置项。",
76|    "hermes sessions browse 打开带搜索功能的交互式会话选择器。",
77|    "hermes sessions stats 显示各平台的会话数和数据库大小。",
78|    "hermes sessions prune --older-than 30 清理旧会话。",
79|    "hermes skills search react --source skills-sh 搜索 skills.sh 公共目录。",
80|    "hermes skills check 扫描已安装的 hub 技能是否有上游更新。",
81|    "hermes skills tap add myorg/skills-repo 添加自定义 GitHub 技能源。",
82|    "hermes skills snapshot export setup.json 导出技能配置用于备份或分享。",
83|    "hermes mcp add github --command npx 从命令行添加 MCP 服务器。",
84|    "hermes mcp serve 将 Hermes 自身作为 MCP 服务器运行。",
85|    "hermes auth add 添加多个 API 密钥用于凭证池轮换。",
86|    "hermes completion bash >> ~/.bashrc 启用所有命令和配置文件的 tab 补全。",
87|    "hermes logs -f 实时跟踪 agent.log。--level WARNING --since 1h 过滤输出。",
88|    "hermes backup 创建整个 Hermes 主目录的 zip 备份。",
89|    "hermes profile create coder 创建独立配置文件，成为独立命令。",
90|    "hermes profile create work --clone 复制当前配置和密钥到新配置文件。",
91|    "hermes update 自动同步新的内置技能到所有配置文件。",
92|    "hermes gateway install 将 Hermes 设置为系统服务（systemd/launchd）。",
93|    "hermes memory setup 配置外部记忆提供商（Honcho、Mem0 等）。",
94|    "hermes webhook subscribe 创建带 HMAC 验证的事件驱动 webhook 路由。",
95|    "在 config.yaml 中设置 display.bell_on_complete: true，长任务完成时发出提示音。",
96|    "设置 display.streaming: true 实时查看模型生成的 token。",
97|    "设置 display.show_reasoning: true 查看模型的链式推理过程。",
98|    "设置 display.compact: true 减少输出中的空白，显示更密集的信息。",
99|    "设置 display.busy_input_mode: queue 将消息排队而非中断 agent，或设为 steer 通过 /steer 在运行中注入。",
100|    "设置 display.resume_display: minimal 跳过会话恢复时的完整对话回顾。",
101|    "设置 compression.threshold: 0.50 控制自动压缩触发时机（默认：上下文的 50%）。",
102|    "设置 agent.max_turns: 200 让 agent 每轮执行更多工具调用步骤。",
103|    "设置 file_read_max_chars: 200000 增加 read_file 调用的最大内容量。",
104|    "设置 approvals.mode: smart 让 LLM 自动审批安全命令并自动拒绝危险命令。",
105|    "在 config.yaml 中设置 fallback_model，自动故障转移到备用提供商。",
106|    "设置 privacy.redact_pii: true 在发送给 LLM 之前哈希化用户 ID 和手机号。",
107|    "设置 browser.record_sessions: true 自动录制浏览器会话为 WebM 视频。",
108|    "在 config.yaml 中设置 worktree: true 始终创建 git worktree（等同于 hermes -w）。",
109|    "设置 security.website_blocklist.enabled: true 阻止特定域名使用 web 工具。",
110|    "设置 cron.wrap_response: false 投递原始 agent 输出，不加 cron 头尾信息。",
111|    "HERMES_TIMEZONE 用任意 IANA 时区字符串覆盖服务器时区。",
112|    "config.yaml 支持环境变量替换：使用 ${VAR_NAME} 语法。",
113|    "config.yaml 中的 Quick commands 可即时运行 shell 命令，零 token 消耗。",
114|    "自定义人格可在 config.yaml 的 agent.personalities 下定义。",
115|    "provider_routing 控制 OpenRouter 提供商排序、白名单和黑名单。",
116|    "execute_code 运行可调用 Hermes 工具的 Python 脚本 — 结果不会进入上下文。",
117|    "delegate_task 默认可并行生成最多 3 个子 agent（delegation.max_concurrent_children），各自拥有独立上下文。",
118|    "web_extract 支持 PDF URL — 传入任何 PDF 链接，自动转换为 markdown。",
119|    "search_files 基于 ripgrep，比 grep 更快 — 用它代替 terminal grep。",
120|    "patch 使用 9 种模糊匹配策略，轻微的空白差异不会导致编辑失败。",
121|    "patch 支持 V4A 格式，可在单次调用中批量编辑多个文件。",
122|    "read_file 在文件未找到时会建议相似的文件名。",
123|    "read_file 自动去重 — 重复读取未变更的文件会返回轻量存根。",
124|    "browser_vision 截图并用 AI 分析 — 适用于验证码和视觉内容。",
125|    "browser_console 可在页面上下文中执行 JavaScript 表达式。",
126|    "image_generate 使用 FLUX 2 Pro 创建图片，并自动 2 倍放大。",
127|    "text_to_speech 将文本转换为语音 — 在 Telegram 上以语音气泡播放。",
128|    "send_message 可从会话内到达任何已连接的消息平台。",
129|    "todo 工具帮助 agent 在会话中跟踪复杂的多步骤任务。",
130|    "session_search 对所有历史对话执行全文搜索。",
131|    "agent 会自动将偏好、纠正和环境信息保存到记忆中。",
132|    "mixture_of_agents 将难题通过 4 个前沿 LLM 协作路由处理。",
133|    "终端命令支持后台模式，配合 notify_on_complete 处理长时间任务。",
134|    "终端后台进程支持 watch_patterns，在特定输出行出现时发出提醒。",
135|    "终端工具支持 6 种后端：local、Docker、SSH、Modal、Daytona 和 Singularity。",
136|    "每个配置文件拥有独立的配置、API 密钥、记忆、会话、技能和定时任务。",
137|    "配置文件名会变成 shell 命令 — 'hermes profile create coder' 创建 'coder' 命令。",
138|    "hermes profile export coder -o backup.tar.gz 创建可移植的配置文件归档。",
139|    "如果两个配置文件意外共享了 bot token，第二个网关会被阻止并显示明确错误。",
140|    "会话在首次交互后自动生成描述性标题 — 无需手动命名。",
141|    "退出时 Hermes 会打印恢复命令，包含会话 ID 和统计信息。",
142|    "hermes sessions export backup.jsonl 导出所有会话用于备份或分析。",
143|    "hermes -r SESSION_ID 通过 ID 恢复任意历史会话。",
144|    "记忆是冻结快照 — 更改仅在下次会话开始时出现在系统提示中。",
145|    "记忆条目会自动扫描提示注入和 exfiltration 模式。",
146|    "agent 有两个记忆存储：个人笔记（约 2200 字符）和用户档案（约 1375 字符）。",
147|    "）通常会自动保存到记忆中。",
148|    "内置 80+ 技能，涵盖 github、创意、MLOps、生产力、研究等领域。",
149|    "每个已安装的技能自动成为斜杠命令 — 输入 / 查看全部。",
150|    "hermes skills install official/security/1password 从仓库安装可选技能。",
151|    "技能可限制为特定操作系统平台 — 有些只在 macOS 或 Linux 上加载。",
152|    "config.yaml 中的 skills.external_dirs 允许从自定义目录加载技能。",
153|    "agent 可以使用 skill_manage 创建自己的技能作为程序性记忆。",
154|    "plan 技能将 markdown 计划保存在活动工作区的 .hermes/plans/ 下。",
155|    "定时任务投递目标包括 telegram、discord、slack、email、sms 等 12+ 平台。",
156|    "如果定时任务响应以 [SILENT] 开头，投递将被抑制 — 适合纯监控任务。",
157|    "定时支持相对延迟（30m）、间隔（every 2h）、cron 表达式和 ISO 时间戳。",
158|    "定时任务在全新的 agent 会话中运行 — 提示必须自包含。",
159|    "安装 faster-whisper 后语音模式无需任何 API 密钥（免费本地语音转文字）。",
160|    "五种 TTS 提供商可选：Edge TTS（免费）、ElevenLabs、OpenAI、NeuTTS（免费本地）、MiniMax。",
161|    "/voice on 在 CLI 中启用语音模式。Ctrl+B 切换按住说话录制。",
162|    "流式 TTS 边生成边播放语音 — 无需等待完整响应。",
163|    "Telegram、Discord、WhatsApp 和 Slack 的语音消息会自动转写。",
164|    "Hermes 支持 18 个平台：Telegram、Discord、Slack、WhatsApp、Signal、Matrix、email 等。",
165|    "hermes gateway install 将其设置为开机自启动的系统服务。",
166|    "钉钉使用 Stream 模式 — 无需 webhook 或公网 URL。",
167|    "BlueBubbles 通过本地 macOS 服务器将 iMessage 接入 Hermes。",
168|    "Webhook 路由支持 HMAC 验证、速率限制和事件过滤。",
169|    "API 服务器提供 OpenAI 兼容端点，兼容 Open WebUI 和 LibreChat。",
170|    "Discord 语音频道模式：bot 加入语音频道，转写语音并回复。",
171|    "group_sessions_per_user: true 在群聊中为每人分配独立会话。",
172|    "/sethome 将当前聊天标记为定时任务投递的主频道。",
173|    "网关支持基于不活跃的超时机制 — 活跃 agent 可无限运行。",
174|    "危险命令审批有 4 个层级：一次、会话、始终（永久白名单）、拒绝。",
175|    "智能审批模式使用 LLM 自动审批安全命令并标记危险命令。",
176|    "SSRF 防护阻止私有网络、环回地址、链路本地地址和云元数据地址。",
177|    "Tirith 预执行扫描检测同形字 URL 欺骗和管道到解释器的模式。",
178|    "MCP 子进程接收过滤后的环境变量 — 只有安全系统变量会通过。",
179|    "上下文文件（.hermes.md、AGENTS.md）在加载前会进行提示注入安全扫描。",
180|    "config.yaml 中的 command_allowlist 永久放行特定 shell 命令模式。",
181|    "上下文到达阈值时自动压缩 — 记忆被刷新，历史被摘要。",
182|    "状态栏会随上下文填充率从黄色变橙色再变红色。",
183|    "~/.hermes/SOUL.md 是 agent 的主要身份定义 — 自定义它来塑造行为。",
184|    "Hermes 从 .hermes.md、AGENTS.md、CLAUDE.md 或 .cursorrules 加载项目上下文（首个匹配）。",
185|    "子目录中的 AGENTS.md 文件会在 agent 导航进入文件夹时被渐进发现。",
186|    "上下文文件上限 20,000 字符，采用智能头尾截断。",
187|    "五种浏览器提供商：local Chromium、Browserbase、Browser Use、Camofox 和 Firecrawl。",
188|    "Camofox 是反检测浏览器 — 带 C++ 指纹伪装的 Firefox 分支。",
189|    "browser_navigate 自动返回页面快照 — 无需再调用 browser_snapshot。",
190|    "browser_vision 加 annotate=true 会在交互元素上叠加编号标签。",
191|    "MCP 服务器在 config.yaml 中配置 — 同时支持 stdio 和 HTTP 传输。",
192|    "按服务器工具过滤：tools.include 白名单，tools.exclude 黑名单特定工具。",
193|    "MCP 服务器在运行时自动生成工具集 — hermes tools 可按平台切换。",
194|    "MCP OAuth 支持：auth: oauth 启用基于 PKCE 的浏览器授权。",
195|    "没有文件修改时检查点零开销 — 默认启用。",
196|    "回滚前会自动保存预回滚快照，可以撤销撤销操作。",
197|    "/rollback 同时撤销对话轮次，agent 不会记得已回滚的变更。",
198|    "检查点使用 ~/.hermes/checkpoints/ 中的影子仓库 — 不会触碰项目的 .git。",
199|    "batch_runner.py 并行处理数百条提示，用于训练数据生成。",
200|    "hermes chat -Q 启用静默模式用于编程调用 — 隐藏横幅和加载动画。",
201|    "轨迹保存（--save-trajectories）捕获完整的工具使用追踪用于模型训练。",
202|    "三种插件类型：通用（工具/钩子）、记忆提供商和上下文引擎。",
203|    "hermes plugins install owner/repo 直接从 GitHub 安装插件。",
204|    "8 种外部记忆提供商可用：Honcho、OpenViking、Mem0、Hindsight 等。",
205|    "插件钩子包括 pre/post_tool_call、pre/post_llm_call 和 transform_terminal_output 用于输出规范化。",
206|    "提示缓存（Anthropic）通过复用缓存的系统提示前缀来降低成本。",
207|    "agent 在后台线程自动生成会话标题 — 零延迟影响。",
208|    "智能模型路由可自动将简单查询路由到更便宜的模型。",
209|    "斜杠命令支持前缀匹配：/h 解析为 /help，/mod 解析为 /model。",
210|    "将文件路径拖入终端会自动附加图片或作为上下文发送。",
211|    "仓库根目录的 .worktreeinclude 列出要复制到 worktree 的 gitignored 文件。",
212|    "hermes acp 将 Hermes 作为 ACP 服务器运行，用于 VS Code、Zed 和 JetBrains 集成。",
213|    "自定义提供商：在 config.yaml 的 custom_providers 下保存命名端点。",
214|    "HERMES_EPHEMERAL_SYSTEM_PROMPT 注入一个永不持久化到历史的系统提示。",
215|    "credential_pool_strategies 支持 fill_first、round_robin、least_used 和 random 轮换。",
216|    "hermes login 支持 Nous 和 OpenAI Codex 提供商的 OAuth 认证。",
217|    "API 服务器同时支持 Chat Completions 和 Responses API，带服务端状态。",
218|    "config.yaml 中设 tool_preview_length: 0 可在加载动画中显示完整文件路径。",
219|    "hermes status --deep 对所有组件运行更深入的诊断检查。",
220|    "定时任务可附加 Python 脚本（--script），其 stdout 作为上下文注入到提示中。",
221|    "定时脚本存放在 ~/.hermes/scripts/，在 agent 运行前执行 — 适合数据收集管道。",
222|    "config.yaml 中的 prefill_messages_file 将少样本示例注入每次 API 调用，永不保存到历史。",
223|    "SOUL.md 完全替换 agent 的默认身份 — 重写它让 Hermes 成为你的专属助手。",
224|    "SOUL.md 首次运行时自动播种默认人格。编辑 ~/.hermes/SOUL.md 进行自定义。",
225|    "/compress <关注主题> 将 60-70% 的摘要预算分配给你的主题，大幅裁剪其余内容。",
226|    "第二次及以后的压缩会更新之前的摘要，而不是从头开始。",
227|    "网关会话重置前，Hermes 在后台自动将重要信息刷入记忆。",
228|    "config.yaml 中设 network.force_ipv4: true 可修复 IPv6 异常服务器上的挂起 — 对 socket 做 monkey-patch。",
229|    "前台终端命令失败时自动重试最多 3 次，采用指数退避（2s、4s、8s）。",
230|    "裸 sudo 命令会被自动改写为从 .env 管道传入 SUDO_PASSWORD — 无需交互提示。",
231|    "execute_code 内置辅助函数：json_parse() 用于容错解析、shell_quote() 和带退避的 retry()。",
232|    "execute_code 的 7 个沙箱工具（web_search、terminal、read/write/search/patch）通过 RPC 调用 — 永远不进入上下文。",
233|    "同一文件区域读取 3 次以上会触发警告。达到 4 次会被硬阻止以防死循环。",
234|    "write_file 和 patch 检测文件是否在上次读取后被外部修改，并发出过期警告。",
235|    "V4A 补丁格式支持添加文件、删除文件和移动文件指令 — 不只是更新。",
236|    "MCP 服务器可以通过 sampling 请求 LLM 补全 — agent 成为服务器的工具。",
237|    "MCP 服务器发送 notifications/tools/list_changed 触发自动工具重新注册，无需重启。",
238|    "delegate_task 加 acp_command: 'claude' 可从任意平台生成 Claude Code 作为子 agent。",
239|    "委托有心跳线程 — 子活动会传播到父进程，防止网关超时。",
240|    "当提供商返回 HTTP 402（需要付款）时，辅助客户端自动回退到下一个。",
241|    "agent.tool_use_enforcement 引导只描述操作而不调用工具的模型 — GPT/Codex 默认自动启用。",
242|    "agent.restart_drain_timeout（默认 60 秒）让运行中的 agent 在网关重启生效前完成工作。",
243|    "agent.api_max_retries（默认 3）控制 agent 重试失败 API 调用的次数 — 降低它可加快回退。",
244|    "网关按会话缓存 AIAgent 实例 — 销毁此缓存会破坏 Anthropic 提示缓存。",
245|    "任何网站都可通过 /.well-known/skills/index.json 暴露技能 — 技能中心会自动发现。",
246|    "~/.hermes/skills/.hub/audit.log 的技能审计日志记录每次安装和移除操作。",
247|    "陈旧的 git worktree 会被自动清理：24-72 小时前且无未推送提交的会在启动时被清除。",
248|    "每个配置文件在 HERMES_HOME/home/ 下有独立的子进程 HOME — 隔离的 git、ssh、npm、gh 配置。",
249|    "HERMES_HOME_MODE 环境变量（八进制，如 0701）设置 Web 服务器遍历的自定义目录权限。",
250|    "容器模式：在 HERMES_HOME 中放置 .container-mode，主机 CLI 会自动 exec 进入容器。",
251|    "Ctrl+C 有 5 个优先级层级：取消录制 → 取消提示 → 取消选择器 → 中断 agent → 退出。",
252|    "agent 运行期间的每次中断都会记录到 ~/.hermes/interrupt_debug.log，带时间戳。",
253|    "BROWSER_CDP_URL 将浏览器工具连接到任何运行中的 Chrome — 接受 WebSocket、HTTP 或 host:port。",
254|    "BROWSERBASE_ADVANCED_STEALTH=true 启用高级反检测，使用自定义 Chromium（Scale 计划）。",
255|    "CLI 在窄于 80 列的终端中自动切换到紧凑模式。",
256|    "Quick commands 支持两种类型：exec（直接运行 shell 命令）和 alias（重定向到另一个命令）。",
257|    "每任务委托模型：config.yaml 中的 delegation.model 和 delegation.provider 将子 agent 路由到更便宜的模型。",
258|    "delegation.reasoning_effort 独立控制子 agent 的思考深度。",
259|    "config.yaml 中的 display.platforms 允许按平台覆盖显示设置：{telegram: {tool_progress: all}}。",
260|    "config.yaml 中的 human_delay.mode 模拟人类打字速度 — 可配置 min_ms/max_ms 范围。",
261|    "配置版本迁移在加载时自动运行 — 新配置项无需手动干预即可出现。",
262|    "GPT 和 Codex 模型获得专门的系统提示指导，用于工具纪律和强制工具使用。",
263|    "Gemini 模型获得定制指令，用于绝对路径、并行工具调用和非交互式命令。",
264|    "config.yaml 中的 context.engine 可设为插件名以使用替代上下文管理策略。",
265|    "超过 8000 token 的浏览器页面会被辅助 LLM 自动摘要后再返回给 agent。",
266|    "压缩器会做一次廉价预处理：超过 200 字符的工具输出在 LLM 运行前被占位符替换。",
267|    "压缩失败时，后续尝试会暂停 10 分钟以避免 API 过度请求。",
268|    "选项，先看全文再决定。",
269|    "录音时音量可视化会根据麦克风 RMS 电平显示 ▁▂▃▄▅▆▇ 条形图。",
270|    "配置文件名不能与现有 PATH 命令冲突 — 'hermes profile create ls' 会被拒绝。",
271|    "hermes profile create backup --clone-all 复制所有内容（配置、密钥、SOUL.md、记忆、技能、会话）。",
272|    "录音快捷键可通过 config.yaml 中的 voice.record_key 配置 — 不限于 Ctrl+B。",
273|    ".cursorrules 和 .cursor/rules/*.mdc 文件会被自动检测并作为项目上下文加载。",
274|    "、exfiltration 尝试等。",
275|    "GPT-5 和 Codex 在消息格式中使用 'developer' 角色代替 'system'。",
276|    "每任务辅助覆盖：config.yaml 中的 auxiliary.vision.provider、auxiliary.compression.model 等。",
277|    "辅助客户端将 'main' 视为提供商别名 — 解析为你实际的主提供商 + 模型。",
278|    "hermes claw migrate --dry-run 预览 OpenClaw 迁移而不写入任何内容。",
279|    "带引号或转义空格的文件路径会自动处理 — 无需手动清理。",
280|    "斜杠命令不会触发大粘贴折叠 — 带大参数的 /command 可以正常工作。",
281|    "中断模式下，agent 执行期间输入的斜杠命令会绕过中断逻辑立即执行。",
282|    "HERMES_DEV=1 绕过容器模式检测，用于本地开发。",
283|    "每个 MCP 服务器有独立的工具集（mcp-servername），可通过 hermes tools 独立切换。",
284|    "config.yaml 中的 MCP ${ENV_VAR} 占位符在服务器生成时解析 — 包括 ~/.hermes/.env 中的变量。",
285|    "受信任仓库（NousResearch）的技能获得 'trusted' 安全级别；社区技能会接受额外扫描。",
286|    "~/.hermes/skills/.hub/quarantine/ 的技能隔离区保存待安全审查的技能。",
287|    "来自可信仓库（NousResearch）的技能获得「可信」安全级别；社区技能会接受额外扫描。",
288|    "技能隔离区 ~/.hermes/skills/.hub/quarantine/ 存放待安全审核的技能。",
289|    "HERMES_CRON_MAX_PARALLEL（默认 4）限制每次 tick 运行的定时任务数，防止突发消耗完你的 API 配额。",
290|    "hermes curator pin <skill> 锁定技能，防止自动归档和 agent 的 skill_manage 工具删除。",
291|    "HERMES_TUI_THEME=light|dark|<hex> 在未设置 COLORFGBG 的终端上强制指定 TUI 主题。",
292|    "display.tool_progress_command: true 在消息平台上启用 /verbose 命令；默认仅限 CLI。",
293|    "batch_runner.py --resume 通过文本匹配已完成的提示，数据集重新排序时不会重跑已完成的任务。",
294|    "hermes chat --source tool 为编程式对话打标签，不会污染 hermes sessions 列表。",
295|    "HERMES_DISABLE_FILE_STATE_GUARD=1 关闭 patch 和 write_file 的「文件自读取后已修改」防护。"
762|]
763|
764|
765|def get_random_tip(exclude_recent: int = 0) -> str:
766|    """Return a random tip string.
767|
768|    Args:
769|        exclude_recent: not used currently; reserved for future
770|            deduplication across sessions.
771|    """
772|    return random.choice(TIPS)
773|